sites:
  - name: Github
    url: https://www.github.com
    maxRedirects: 10
  - name: Wikipedia
    url: https://www.wikipedia.org
  - name: Google
    url: https://www.google.com
  - name: Yahoo
    url: https://in.yahoo.com
  - name: Test
    url: https://thissitedoesnotexist.koj.co/